#!/bin/bash
echo "Enter 1 to launch 'nano'"
echo "Enter 2 to launch 'vim'"
echo "Enter 3 to launch 'links'"
echo "Enter 4 to  exit"
read string
case $string in
1 )
nano
;;
2 )
vi
;;
3 )
links
;;
4 )
exit
;;
esac
