#!/bin/bash

createDir()
{
	name="Backup-$dateNow"
	mkdir /home/user/$name
	echo "Directory created"
	for file in $(ls -1 /home/user/source); do
		cp -a /home/user/source/"$file" /home/user/$name
	done
	echo "$dateNow a new directory was created '$name' with backupcopies:" >> /home/user/backup-report
	for file in $(ls -1 /home/user/$name); do
        echo "$file" >> /home/user/backup-report
    done

}

addBackup()
{
touch .newFiles
touch .newVersion
backupDir=$(find /home/user -name "Backup-[0-9]*-[0-9]*-[0-9]*" -type d -ctime -7)
name=$(sed "s/\/home\/user\///" <<< $backupDir)
for file in $(ls -1 /home/user/source); do
	if ! [ -f "$backupDir/$file" ];then
		cp -a /home/user/source/"$file" $backupDir
		echo "$file" >> .newFiles
	else
		if [ $(wc -c /home/user/source/"$file" | sed "s/\ .*$//") -ne $(wc -c $backupDir/"$file" | sed "s/\ .*$//") ];then
			mv $backupDir/"$file" $backupDir/"$file".$dateNow
			cp -a /home/user/source/"$file" $backupDir
			echo "$file $file.$dateNow" >> .newVersion
		fi
	fi
	done
echo "$dateNow changes have been made to the directory '$name' with backupcopies:" >> /home/user/backup-report
cat .newFiles | while read -r line; do
	echo "$line" >> /home/user/backup-report
done
cat .newVersion | while read -r line; do
	echo "$line" >> /home/user/backup-report
done
}

dateNow=$(date +"%Y-%m-%d")
if [ -d /home/user/Backup-[0-9]*-[0-9]*-[0-9]* ]; then
	dateOld=$(find /home/user -name "Backup-[0-9]*-[0-9]*-[0-9]*" -type d -ctime +7 | sed "s/\/home\/user\/Backup-//")
	dateOldS=$(date -d "$dateOld" +"%s")
	dateNowS=$(date -d "$dateNow" +"%s")
	let "daysPass = dateNowS - dateOldS"
	let "daysPass = daysPass / 60 / 60 / 24"
	if [[ $daysPass -gt 7 ]]; then
		createDir
	else
		addBackup
	fi
else
	createDir
fi
