#!/bin/bash
if [[ $# -ne 1 ]]; then
        echo "Parameter error"
        exit
fi
count=$(grep -c "$1;" ~/.trash.log)
if [[ $count -eq 0 ]]; then
        echo "File not found"
        exit
else
grep "$1" ~/.trash.log | while read -r line; do
        name="$1"
        path=$(grep -o "/.*"$name";" <<< "$line"| sed 's/;//')
        link=$(grep -o "[0-9]*$" <<< "$line")
        echo -n "Recover '$path'? (enter y/n):"
        read answer </dev/tty
        case "$answer" in
        "y")
                d=$(sed "s/\/"$name"/\//" <<< "$path")
                if [[ !(-d "$d") ]]; then
                        path="$HOME/"$name""
                        echo -e "Directory "$d" does not exis\nRecovery path: "$HOME/""
                fi
                if [[ -f "$path" ]]; then
                        while true; do
                        echo -ne "Such file already exists\nChange file name? (enter y/n):"
                        read answ </dev/tty
                        case "$answ" in
                        "y")
                                echo -n "Enter new name: "
                                read newName </dev/tty
                                newPath=$(sed "s/\/"$name"/\/"$newName"/" <<< "$path")
                                if [[ !(-f "$newPath") ]];
                                        then
                                                name="$newName"
                                                path="$newPath"
                                                break
                                fi
                        ;;
                        *)
                        exit
                        ;;
                        esac
                        done
                fi
                ln ~/.trash/"$link" "$path"
                rm ~/.trash/"$link"
                sed -i "/"$link"$/d" ~/.trash.log
                exit
        ;;
        *)
                :
        ;;
        esac
done
fi
