#!/bin/bash
ppid=0
art=0
count=0
b=""
while read a
do
if [[ -n $a ]]
then
newppid=$(echo $a | grep -Ehsio "Parent_ProcessID=[0-9]+" | grep -o "[0-9]\+")
newART=$(echo $a | grep -Ehsio "Average_Running_Time=[0-9]+" | grep -o "[0-9]\+" | awk '{printf("%s",$1)}')
if [[ $ppid == $newppid ]]
then
art=$(echo "$art+$newART" | bc -l -q)
count=$(echo "$count+1" | bc -l -q)
else
art=$(echo "$art/$count" | bc -l -q)
if [[ -n $b ]]
then
b=$b"Average_Sleeping_Children_of_ParentID="$ppid" is "$art$'\n'
fi
art=$newART
ppid=$newppid
count=1
fi
b=$b$a$'\n'
fi
done < result_4
art=$(echo "$art/$count" | bc -l -q)
if [[ -n $b ]]
then
b=$b"Average_Sleeping_Children_of_ParentID="$ppid" is "$art$'\n'
fi
echo "$b" > result_5
