#!/bin/bash
mkdir $HOME/test && echo "catalog test was created successfully" > ~/report && touch $HOME/test/$(date +"%d.%m.%Y_%H:%M:%S")
ping www.net_nikogo.ru || echo "$(date +"%d.%m.%y_%H:%M:%S") site unavailable" >> ~/report
